objects/UspsAddress__c.object
<CustomObject>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CarrierRoute__c</fullName>
        <label>Carrier Route</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryPoint__c</fullName>
        <label>Delivery Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirmName__c</fullName>
        <label>Firm Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip4__c</fullName>
        <label>Zip 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip5__c</fullName>
        <label>Zip 5</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>USPS Address</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>USPS Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>USPS Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UspsAddressValidateRequest__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>UspsAddress__c</referenceTo>
        <relationshipName>AddressValidationRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsIncludeOptionalElements__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include Optional Elements</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsReturnCarrierRoute__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Return Carrier Route</label>
        <type>Checkbox</type>
    </fields>
    <label>USPS Address Validate Request</label>
    <nameField>
        <displayFormat>UAVR-{00000000}</displayFormat>
        <label>USPS Address Validation Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>USPS Address Validate Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UspsAddressValidateResponse__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>USPS Address</label>
        <referenceTo>UspsAddress__c</referenceTo>
        <relationshipLabel>USPS Address Validate Responses</relationshipLabel>
        <relationshipName>UspsAddressValidateResponses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>USPS Address Validate Response</label>
    <nameField>
        <displayFormat>UAVR-{00000000}</displayFormat>
        <label>USPS Address Validation Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>USPS Address Validate Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UspsSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>USPS Web Tools API</description>
    <fields>
        <fullName>UserId__c</fullName>
        <description>USERID attribute used for API authentication</description>
        <inlineHelpText>USERID attribute used for API authentication</inlineHelpText>
        <label>User ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>USPS Setting</label>
</CustomObject>

classes/XmlServiceTest.cls
@isTest
private class XmlServiceTest {

	@testSetup
	private static void setup() {
		
		// Create a custom setting
		insert new UspsSetting__c(UserId__c = 'TEST');
	}
	
	/**
	 * Deserialize XML content for an `AddressValidateResponse` as expected
	 * from a successful request to validate an address.
	 *
     * <?xml version="1.0" encoding="UTF-8"?>
     * <AddressValidateResponse>
     *     <Address ID="0">
     *         <FirmName>SLALOM</FirmName>
     *         <Address1>STE 300</Address1>
     *         <Address2>316 STUART ST</Address2>
     *         <City>BOSTON</City>
     *         <State>MA</State>
     *         <Zip5>02116</Zip5>
     *         <Zip4>5242</Zip4>
     *         <DeliveryPoint>16</DeliveryPoint>
     *         <CarrierRoute>C027</CarrierRoute>
     *     </Address>
     * </AddressValidateResponse>
     */
    @isTest
    private static void deserializeAddressValidateResponse() {
		
		// Validate the given
		String content = String.join(new List<String> {
			'<?xml version="1.0" encoding="UTF-8"?>',
			'<AddressValidateResponse>',
			'    <Address ID="0">',
			'        <FirmName>SLALOM</FirmName>',
			'        <Address1>STE 300</Address1>',
			'        <Address2>316 STUART ST</Address2>',
			'        <City>BOSTON</City>',
			'        <State>MA</State>',
			'        <Zip5>02116</Zip5>',
			'        <Zip4>5242</Zip4>',
			'        <DeliveryPoint>16</DeliveryPoint>',
			'        <CarrierRoute>C027</CarrierRoute>',
			'    </Address>',
			'</AddressValidateResponse>'
		}, '\r\n');
		
		// Do the when
		Test.startTest();
		
		XmlService xml = XmlService.getInstance();
		
		UspsAddressValidateResponse__c res =
				(UspsAddressValidateResponse__c)xml.deserialize(
						content, UspsAddressValidateResponse__c.sobjectType);
		
		// Validate the then
		Test.stopTest();
		
		System.assertEquals('SLALOM', res.Address__r.FirmName__c);
		System.assertEquals('STE 300', res.Address__r.Address1__c);
		System.assertEquals('316 STUART ST', res.Address__r.Address2__c);
		System.assertEquals('BOSTON', res.Address__r.City__c);
		System.assertEquals('MA', res.Address__r.State__c);
		System.assertEquals('02116', res.Address__r.Zip5__c);
		System.assertEquals('5242', res.Address__r.Zip4__c);
		System.assertEquals('16', res.Address__r.DeliveryPoint__c);
		System.assertEquals('C027', res.Address__r.CarrierRoute__c);
    }
    
	/**
	 * Serialize an object that represents the following XML data for
	 * an `AddressValidateRequest`.
	 *
	 * <AddressValidateRequest USERID="XXXXX">
	 *   <IncludeOptionalElements>true</IncludeOptionalElements>
	 *   <ReturnCarrierRoute>true</ReturnCarrierRoute>
	 *   <Address ID="0">  
	 *     <FirmName />   
	 *     <Address1 />   
	 *     <Address2>205 bagwell ave</Address2>   
	 *     <City>nutter fort</City>   
	 *     <State>wv</State>   
	 *     <Zip5></Zip5>   
	 *     <Zip4></Zip4> 
	 *   </Address>      
	 * </AddressValidateRequest>
	 */
	@isTest
	private static void serializeAddressValidateRequest() {
		
		// Validate the given
		UspsAddressValidateRequest__c req = new UspsAddressValidateRequest__c(
				IsIncludeOptionalElements__c = true,
				IsReturnCarrierRoute__c = true,
				Address__r = new UspsAddress__c(
						Address2__c = '205 bagwell ave',
						City__c = 'nutter fort',
						State__c = 'wv'));
		
		// Do the when
		Test.startTest();
		
		XmlService xml = XmlService.getInstance();
		String content = xml.serialize((Sobject)req);
		
		// Validate the then
		Test.stopTest();
		
		String expectedContent = String.join(new List<String> {
			'<AddressValidateRequest USERID="TEST">',
			'<IncludeOptionalElements>true</IncludeOptionalElements>',
			'<ReturnCarrierRoute>true</ReturnCarrierRoute>',
			'<Address ID="0">',
			'<FirmName />',
			'<Address1 />',
			'<Address2>205 bagwell ave</Address2>',
			'<City>nutter fort</City>',
			'<State>wv</State>',
			'<Zip5 />',
			'<Zip4 />',
			'</Address>',
			'</AddressValidateRequest>'
		}, '');
		
		System.assertEquals(expectedContent, content);
	}
}